Models/Series.cs
namespace NewsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Series
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Series()
        {
            Posts = new HashSet<Post>();
        }

        [Key]
        public int series_id { get; set; }

        [Required]
        [StringLength(200)]
        public string seriesName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}

Controllers/EmailController.cs
using System.Net;
using System.Net.Mail;
using System.Web.Helpers;
using System.Web.Mvc;
using NewsWebsite.ViewModel;

namespace NewsWebsite.Controllers
{
    public class EmailController : Controller
    {
        public ActionResult SendMail()
        {
            return View();
            
        }
        [HttpPost]
        // GET
        public ActionResult SendMail(string useremail)
        {
            MailMessage mm = new MailMessage("emailfortest612@gmail.com", useremail);
            mm.Subject = "THANK YOU FOR SUBCRIBING";
            mm.Body = "We will send you news soon";
            mm.IsBodyHtml = false;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("emailfortest612@gmail.com", "asidsdamad1");
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = nc;
            smtp.Send(mm);

            ViewBag.msg = "Email have been sent successfully...";
            return View();
        }
    }
}

Controllers/HomeController.cs
using NewsWebsite.CommonData;
using NewsWebsite.Models;
using NewsWebsite.Repository;
using NewsWebsite.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsWebsite.Controllers
{
    public class HomeController : Controller
    {
        UnitOfWork db = new UnitOfWork(new Models.NewsDbContext());
        public ActionResult Index()
        {
            ViewBag.Title = db.infoRepository.FindByID(1).web_name;
            return View(db.postRepository.AllPosts().Where(m => m.status == true)
                .OrderByDescending(m => m.create_date).Take(6).ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ViewPost(string title)
        {
            if (!String.IsNullOrWhiteSpace(title))
            {
                Post p = db.postRepository.FindBySlug(title);
                if (p != null)
                {
                    p.view_count++;
                    db.Commit();
                    List<TagList> tagLists = p.Tags.Select(m => new TagList
                    {
                        id = m.tag_id,
                        name = m.tag_name,
                        slug = SlugGenerator.SlugGenerator.GenerateSlug(m.tag_name) + "-" + m.tag_id
                    }).ToList();
                    return View(new ViewPostViewModel
                    {
                        post_id = p.post_id,
                        dynasty = p.dynasty,
                        create_date = p.create_date,
                        //firstTag = tagLists.FirstOrDefault().name,
                        post_review = p.post_review,
                        post_tag = p.post_tag,
                        AvatarImage = p.avatar_image,
                        edit_date = p.edit_date,
                        post_content = p.post_content,
                        post_teaser = p.post_teaser,
                        post_title = p.post_title,
                        post_type = p.post_type,
                        Rated = p.rated,
                        userid = p.user_id,
                        ViewCount = p.view_count,
                        tagLists = tagLists,

                    });
                }
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
        public ActionResult Category(int? id, int? page)
        {
            if (id != null)
            {
                int pageSize = 15;
                int pageIndex = 1;
                //IPagedList<Tbl_POST> post = null;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                Tag tag = db.tagRepository.FindByID(id.Value);
                if (tag != null)
                {
                    using (NewsDbContext conn = db.Context)
                    {
                        var result = (
                            // instance from context
                            from a in conn.Tags
                                // instance from navigation property
                            from b in a.Posts
                                //join to bring useful data
                            join c in conn.Posts on b.post_id equals c.post_id
                            where a.tag_id == id && b.status == true
                            orderby b.create_date descending
                            select new ListPostViewModel
                            {
                                post_id = c.post_id,
                                post_title = c.post_title,
                                post_teaser = c.post_teaser,
                                ViewCount = c.view_count,
                                AvatarImage = c.avatar_image,
                                create_date = c.create_date,
                                slug = c.post_slug
                            }).ToPagedList(pageIndex, pageSize);
                        ViewBag.catname = tag.tag_name;
                        return View((PagedList<ListPostViewModel>)result);
                    }
                }
                return HttpNotFound();
            }

            return View("CategoryAll");

        }
        public ActionResult Series(int? id, int? page)
        {
            if (id != null)
            {
                int pageSize = 15;
                int pageIndex = 1;
                //IPagedList<Tbl_POST> post = null;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                Series series = db.seriesRepository.FindByID(id.Value);
                if (series != null)
                {
                    using (NewsDbContext conn = db.Context)
                    {
                        var result = (
                            // instance from context
                            from a in conn.Series
                            // instance from navigation property
                            from b in a.Posts
                            //join to bring useful data
                            join c in conn.Posts on b.post_id equals c.post_id
                            where a.series_id == id && b.status == true
                            orderby b.create_date descending
                            select new ListPostViewModel
                            {
                                post_id = c.post_id,
                                post_title = c.post_title,
                                post_teaser = c.post_teaser,
                                ViewCount = c.view_count,
                                AvatarImage = c.avatar_image,
                                create_date = c.create_date,
                                slug = c.post_slug
                            }).ToPagedList(pageIndex, pageSize);
                        ViewBag.catname = series.seriesName;
                        return View((PagedList<ListPostViewModel>)result);
                    }
                }
                return HttpNotFound();
            }

            return View("SeriesAll");

        }
        public ActionResult Dynasty(int? dynasty, int? page)
        {
            if(dynasty != null)
            {
                int pageSize = 10;
                int pageIndex = 1;
                IPagedList<ListPostViewModel> post = null;
                Dynasty d = (Dynasty) dynasty;
                ViewBag.catname = d.GetDisplayName();
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                post = db.postRepository.AllPosts()
                    .Where(m => m.status)
                    .Where(m => m.dynasty.Equals(d.ToString()))
                    .OrderByDescending(m => m.create_date)
                     .Select(c => new ListPostViewModel
                     {
                         post_id = c.post_id,
                         post_title = c.post_title,
                         post_teaser = c.post_teaser,
                         ViewCount = c.view_count,
                         AvatarImage = c.avatar_image,
                         create_date = c.create_date,
                         tagsname = c.Tags.FirstOrDefault().tag_name,
                         slug = c.post_slug
                     }).ToPagedList(pageIndex, pageSize);
                return View((PagedList<ListPostViewModel>)post);
            }
            return View("DynastyAll");
        }

        public ActionResult Search(SearchViewModel model, int? page)
        {
            int pageIndex = 1;
            int pageSize = 8;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<ListPostViewModel> post = new List<ListPostViewModel>().ToPagedList(pageIndex, pageSize);
            List<Tag> tagList = new List<Tag>();
            tagList.AddRange(model.post_tag.Where(m => m.Selected)
                .Select(m => new Tag { tag_id = int.Parse(m.Value), tag_name = m.Text })
                );
            ViewBag.title = model.title;
            ViewBag.metaTag = model.meta_tag;
            bool title = String.IsNullOrEmpty(model.title);
            bool tag = tagList.Count == 0;
            bool dynasty = model.Dynasty == null;
            var check = 0;
            if(title)
            {
                if (tag)
                {
                    if (dynasty) check = 1; // ko chọn  
                    else check = 5;         // tìm phạm vi
                }
                else
                {
                    if (dynasty) check = 4; // chỉ tag 
                    else check = 8;         // phạm vi vs tag 
                }
            }
            if (!title)
            {
                if (tag)
                {
                    if (dynasty) check = 3; // chỉ tiêu đề
                    else check = 7;         // phạm vi vs tiêu đề 
                }
                else
                {
                    if (dynasty) check = 6; // tiêu đề vs phạm vi
                    else check = 2;         // tìm cả 3 
                }
            }
            //if (title && tag && dynasty)
            //{
            //    check = 1;
            //}
            //else if (!title && !tag && !dynasty)
            //{
            //    // cả 3 cái đều ko null
            //    check = 2;
            //}
            //else if (!title && tag && dynasty)
            //{
            //    // chỉ title
            //    check = 3;
            //}
            //else if (title && !tag && dynasty)
            //{
            //    // chỉ tag
            //    check = 4;
            //}
            //else if (title && tag && !dynasty)
            //{
            //    // chỉ DN
            //    check = 5;
            //}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information 22.</p>

Views/Home/Category.cshtml
@model PagedList.PagedList<NewsWebsite.ViewModel.ListPostViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = ViewBag.catname + " | NT Hiếu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}

<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>@ViewBag.catname</b></h4>
                        @foreach (var item in Model)
                        {
                            <a class="link row oflow-hidden pos-relative mb-md-2 mb-1 dplay-block ml-md-1" href="/bai-viet/@item.slug">
                                <div class="col-md-4 col-12 pl-md-0" style="height:auto">
                                    <img src="~/Upload/images/@item.AvatarImage" alt="@item.post_title" onerror="this.onerror=null;" />
                                </div><div class="col-md-8 col-12">
                                    <div class="min-h-100x">
                                        <h5><b>@item.post_title</b></h5>
                                        <p>@(item.post_teaser.Length >= 150 ? item.post_teaser.Substring(0, 150) : item.post_teaser + "..")</p>
                                        <ul>
                                            <li class="latest"><span class="fa fa-calendar mr-1" style="color:#777777"></span>@String.Format("{0:dd-MM-yyyy}", item.create_date)</li>
                                        </ul>
                                        @*<h6 class="color-lite-black pt-2">Jan 25, 2018</h6>*@
                                    </div>
                                </div>
                            </a>
                        }
                        @{
                            if (Model.PageCount > 1)
                            {
                                <nav aria-label="Page navigation example" style="text-align:center">
                                    @Html.PagedListPager(Model, page => Url.Action("Category", new { page }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
                                </nav>
                            }
                        }
                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/CategoryAll.cshtml
@{
    ViewBag.Title = "Duyệt theo các danh mục | NT Hiếu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}

<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>DUYỆT THEO DANH MỤC</b></h4>
                        <div class="float-left-right text-center mt-40 mt-sm-20">
                            <ul class="mb-30 list-li-mt-10 list-li-mr-5 list-a-plr-15 list-a-ptb-7 list-a-bg-grey list-a-br-2 list-a-hvr-primary ">

                                @foreach (var i in data.GetListTags())
                                {
                                    <li><a href="/danh-muc/@SlugGenerator.SlugGenerator.GenerateSlug(i.TagName.ToLower())-@i.TagID">@i.TagName</a></li>
                                }
                            </ul>
                        </div>

                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Dynasty.cshtml
@model PagedList.PagedList<NewsWebsite.ViewModel.ListPostViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title = ViewBag.catname + " | NT Hiếu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}

<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>@ViewBag.catname</b></h4>
                        @foreach (var item in Model)
                        {
                            <div class="link row oflow-hidden pos-relative mb-md-2 mb-1 dplay-block ml-md-1">
                                <div class="col-md-4 col-12 pl-md-0 pb-sm-2" style="height:auto">
                                    <a href="/bai-viet/@item.slug">
                                        <img src="~/Upload/images/@item.AvatarImage" alt="@item.post_title"
                                             onerror="this.onerror=null;" />
                                    </a>
                                </div><div class="col-md-8 col-12 pt-sm-2 pt-md-0">
                                    <div class="min-h-100x">
                                        <h5> <a class="font-weight-bold" href="/bai-viet/@item.slug">@item.post_title</a></h5>
                                        <p>@(item.post_teaser.Length >= 150 ? item.post_teaser.Substring(0, 150) : item.post_teaser + "..")</p>
                                        @if (!String.IsNullOrWhiteSpace(item.post_review))
                                        {<p>
                                                Review: @item.post_review
                                            </p>
                                        }

                                        <ul>
                                            <li class="latest"><span class="fa fa-calendar mr-1" style="color:#777777"></span>@String.Format("{0:dd-MM-yyyy}", item.create_date)</li>
                                            <li class="latest"><span class="fa fa-tags mr-1" style="color:#777777"></span>@item.tagsname</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }
                        @{
                            if (Model.PageCount > 1)
                            {
                                <nav aria-label="Page navigation example" style="text-align:center">
                                    @Html.PagedListPager(Model, page => Url.Action("Dynasty", new { page }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
                                </nav>
                            }
                        }
                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/DynastyAll.cshtml
@{
    ViewBag.Title = "Duyệt theo khu vực | NT Hiếu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}
<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>DUYỆT THEO KHU VỰC</b></h4>
                        <div class="float-left-right text-center mt-40 mt-sm-20">
                            <ul class="mb-30 list-li-mt-10 list-li-mr-5 list-a-plr-15 list-a-ptb-7 list-a-bg-grey list-a-br-2 list-a-hvr-primary ">
                                @foreach (var i in data.GetEnumShowList())
                                {
                                    <li><a href="/khu-vuc/@i.slug-@i.value">@i.showname</a></li>
                                }
                            </ul>
                        </div>

                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<NewsWebsite.Models.Post>
@{
    //ViewBag.Title = "Home Page";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}


<div class="row">
    <div class="col-12">
        <!-- Start top-post Area -->
        @Html.Partial("_HotPost")
        <!-- End top-post Area -->
    </div>
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>BÀI VIẾT GẦN ĐÂY</b></h4>
                        @foreach (var item in Model)
                        {
                            <div class="link row oflow-hidden pos-relative mb-md-2 mb-1 dplay-block ml-md-1">
                                <div class="col-md-4 col-12 pl-md-0 pb-sm-2" style="height:auto">
                                    <a href="/bai-viet/@item.post_slug">
                                        <img src="~/Upload/images/@item.avatar_image" alt="@item.post_title"
                                             onerror="this.onerror=null;this.src='/Content/web/images/top-post1.jpg';" />
                                    </a>
                                </div><div class="col-md-8 col-12 pt-sm-2 pt-md-0">
                                          <div class="min-h-100x">
                                              <h5> <a class="font-weight-bold" href="/bai-viet/@item.post_slug">@item.post_title</a></h5>
                                              <p>@(item.post_teaser.Length >= 150 ? item.post_teaser.Substring(0, 150) : item.post_teaser + "..")</p>
                                              @if (!String.IsNullOrWhiteSpace(item.post_review))
                                              {<p>
                                                      Review: @item.post_review
                                                  </p>
                                              }

                                              <ul>
                                                  <li class="latest"><span class="fa fa-calendar mr-1" style="color:#777777"></span>@String.Format("{0:dd-MM-yyyy}", item.create_date)</li>
                                                  <li class="latest"><span class="fa fa-tags mr-1" style="color:#777777"></span>@item.Tags.FirstOrDefault().tag_name</li>
                                              </ul>
                                          </div>
                                </div>
                            </div>
                        }

                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())

                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/Search.cshtml
@model PagedList.PagedList<NewsWebsite.ViewModel.ListPostViewModel>
@using PagedList.Mvc;
@{
    ViewBag.Title =  String.IsNullOrEmpty(ViewBag.stitle) ? "Kết quả tìm kiếm " : ViewBag.stitle;
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
    string tt = String.IsNullOrWhiteSpace(ViewBag.stitle) ? "" : "CHO: " + ViewBag.stitle;
}

<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <!--KHU VỰC TÌM KIẾM-->
                        @Html.Partial("_Search", new NewsWebsite.ViewModel.SearchViewModel())
                        <!--kết thúc tìm kiếm-->

                        <h4 class="p-title ml-md-1 pt-4"><b>KẾT QUẢ TÌM KIẾM @tt.ToUpper()</b></h4>
                        @foreach (var item in Model)
                        {
                            <div class="link row oflow-hidden pos-relative mb-md-2 mb-1 dplay-block ml-md-1">
                                <div class="col-md-4 col-12 pl-md-0 pb-sm-2" style="height:auto">
                                    <a href="/bai-viet/@item.slug">
                                        <img src="~/Upload/images/@item.AvatarImage" alt="@item.post_title"
                                             onerror="this.onerror=null;" />
                                    </a>
                                </div><div class="col-md-8 col-12 pt-sm-2 pt-md-0">
                                    <div class="min-h-100x">
                                        <h5> <a class="font-weight-bold" href="/bai-viet/@item.slug">@item.post_title</a></h5>
                                        <p>@(item.post_teaser.Length >= 150 ? item.post_teaser.Substring(0, 150) : item.post_teaser + "..")</p>
                                        @if (!String.IsNullOrWhiteSpace(item.post_review))
                                        {<p>
                                                Review: @item.post_review
                                            </p>
                                        }

                                        <ul>
                                            <li class="latest"><span class="fa fa-calendar mr-1" style="color:#777777"></span>@String.Format("{0:dd-MM-yyyy}", item.create_date)</li>
                                            <li class="latest"><span class="fa fa-tags mr-1" style="color:#777777"></span>@item.tagsname</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }
                        @{
                            if (Model.PageCount > 1)
                            {
                                <nav aria-label="Page navigation example" style="text-align:center">
                                    @Html.PagedListPager(Model, page => Url.Action("Search", new { page, title = ViewBag.stitle }), new PagedListRenderOptions { UlElementClasses = new string[] { "pagination" }, LiElementClasses = new string[] { "page-item" } })
                                </nav>
                            }
                        }
                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/SeriesAll.cshtml
@{
    ViewBag.Title = "Duyệt theo các series bài viết | NT Hiếu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}

<div class="row">
    <div class="col-12">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h4 class="p-title ml-md-1"><b>DUYỆT THEO SERIES BÀI VIẾT</b></h4>
                        <div class="float-left-right text-center mt-40 mt-sm-20">
                            <ul class="mb-30 list-li-mt-10 list-li-mr-5 list-a-plr-15 list-a-ptb-7 list-a-bg-grey list-a-br-2 list-a-hvr-primary ">

                                @foreach (var i in data.GetListSeries())
                                {
                                    <li><a href="/series/@SlugGenerator.SlugGenerator.GenerateSlug(i.SerieName.ToLower())-@i.SerieID">@i.SerieName</a></li>
                                }
                            </ul>
                        </div>

                    </div>
                    <!-- container -->

                    <div class="col-md-4">
                        <!-- Phổ biến -->
                        @Html.Partial("_PopularPost", data.GetPopularPost())
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Views/Home/_PopularPost.cshtml
@model IEnumerable<NewsWebsite.Models.Post>
@{
    NewsWebsite.CommonData.GetData data = new NewsWebsite.CommonData.GetData();
}
<div class="pl-20 pl-md-0">
    <div class="popular-post">
        <h4 class="p-title"><b>PHỔ BIẾN</b></h4>
        @foreach (var item in Model)
        {
            <a class="link oflow-hidden pos-relative mb-20 dplay-block" href="/bai-viet/@item.post_slug">
                <div style="background-image:url(/Upload/images/@item.avatar_image)" class="wh-100x abs-tlr img-bg-head"></div>
                <div class="ml-120 min-h-100x smallpop">
                    <h5 class="poppost">@item.post_title</h5>
                    <h6 class="color-lite-black pt-2 mb-1">
                        <i class="fa fa-calendar-o mr-1"></i>@String.Format("{0:dd/MM/yyyy}", item.create_date)  <i class="fa fa-eye mr-1 ml-2"></i> @item.view_count
                    </h6>
                </div>
            </a>
        }
    </div>
    <div class="mtb-50 mb-md-0">
        
        @Html.Action("SendMail", "Email")
    </div>
    <div class="mtb-50 mb-md-0">
        <h4 class="p-title"><b>DANH MỤC</b></h4>
        <div class="widget-content list-label-widget-content mt-1">
            <ul>
                @foreach (var i in data.GetListTags())
                {
                    <li><a href="/danh-muc/@SlugGenerator.SlugGenerator.GenerateSlug(i.TagName.ToLower())-@i.TagID">@i.TagName</a></li>
                }
            </ul>
            <div class="clear"></div>
        </div>
    </div>
</div>